"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CONNECT = exports.CREATE_RECORD = exports.USER_JOINED = exports.CONNECTION = exports.DELETE_RECORD = exports.SAVE_RECORD = exports.CHANGED_RECORD = exports.CONNECTED_USERS = exports.JOIN_ROOM = void 0;
exports.JOIN_ROOM = 'join-room';
exports.CONNECTED_USERS = 'connected-users';
exports.CHANGED_RECORD = 'change-record';
exports.SAVE_RECORD = 'save-record';
exports.DELETE_RECORD = 'delete-record';
exports.CONNECTION = 'connection';
exports.USER_JOINED = 'user-join';
exports.CREATE_RECORD = 'create-record';
exports.CONNECT = 'connect';
